//! hello-provider — minimal example stui plugin.
//!
//! This is the reference implementation every plugin author can copy.
//! It returns hardcoded results so it works without any API keys or network.
//!
//! ## Build
//! ```bash
//! rustup target add wasm32-wasip1
//! cargo build --target wasm32-wasip1 --release
//! cp target/wasm32-wasip1/release/hello_provider.wasm \
//!    ~/.stui/plugins/hello-provider/plugin.wasm
//! ```

use stui_plugin_sdk::prelude::*;

// ── Plugin implementation ─────────────────────────────────────────────────────

#[derive(Default)]
pub struct HelloProvider;

impl StuiPlugin for HelloProvider {
    fn name(&self) -> &str { "hello-provider" }
    fn version(&self) -> &str { "0.1.0" }
    fn plugin_type(&self) -> PluginType { PluginType::Provider }

    fn search(&self, req: SearchRequest) -> PluginResult<SearchResponse> {
        plugin_info!("hello-provider: search query='{}' tab='{}'", req.query, req.tab);

        let q = req.query.to_lowercase();

        // Filter the static catalog by query
        let items: Vec<PluginEntry> = CATALOG
            .iter()
            .filter(|e| {
                // tab filter
                let tab_match = match req.tab.as_str() {
                    "movies"  => e.media_type == "movie",
                    "series"  => e.media_type == "series",
                    _         => true,
                };
                // query filter (empty = return all)
                let q_match = q.is_empty()
                    || e.title.to_lowercase().contains(&q)
                    || e.genre.to_lowercase().contains(&q);
                tab_match && q_match
            })
            .take(req.limit as usize)
            .map(|e| PluginEntry {
                id:          format!("hello:{}", e.id),
                title:       e.title.into(),
                year:        Some(e.year.into()),
                genre:       Some(e.genre.into()),
                rating:      Some(e.rating.into()),
                description: Some(e.description.into()),
                poster_url:  None, // no poster in this example
                imdb_id:     Some(e.id.into()),
            })
            .collect();

        let total = items.len() as u32;
        PluginResult::ok(SearchResponse { items, total })
    }

    fn resolve(&self, req: ResolveRequest) -> PluginResult<ResolveResponse> {
        plugin_info!("hello-provider: resolve entry_id='{}'", req.entry_id);

        // In a real plugin this would hit a streaming API.
        // We return a placeholder so the resolve path can be tested.
        PluginResult::ok(ResolveResponse {
            stream_url: format!("https://example.com/stream/{}", req.entry_id),
            quality:    Some("1080p".into()),
            subtitles:  vec![
                SubtitleTrack {
                    language: "en".into(),
                    url:      format!("https://example.com/subs/{}.en.srt", req.entry_id),
                    format:   "srt".into(),
                }
            ],
        })
    }
}

// ── Static catalog ────────────────────────────────────────────────────────────

struct StaticEntry {
    id: &'static str,
    title: &'static str,
    year: &'static str,
    genre: &'static str,
    rating: &'static str,
    description: &'static str,
    media_type: &'static str, // "movie" | "series"
}

const CATALOG: &[StaticEntry] = &[
    StaticEntry {
        id: "tt15398776", title: "Oppenheimer", year: "2023",
        genre: "Drama", rating: "8.9",
        description: "The story of J. Robert Oppenheimer and the atomic bomb.",
        media_type: "movie",
    },
    StaticEntry {
        id: "tt1160419", title: "Dune: Part Two", year: "2024",
        genre: "Sci-Fi", rating: "8.8",
        description: "Paul Atreides unites with the Fremen.",
        media_type: "movie",
    },
    StaticEntry {
        id: "tt21264584", title: "Shōgun", year: "2024",
        genre: "Historical Drama", rating: "9.0",
        description: "A powerful Japanese warlord and an English navigator.",
        media_type: "series",
    },
    StaticEntry {
        id: "tt14544192", title: "The Bear", year: "2024",
        genre: "Drama", rating: "8.6",
        description: "A young chef returns home to run the family restaurant.",
        media_type: "series",
    },
    StaticEntry {
        id: "tt12840396", title: "Fallout", year: "2024",
        genre: "Sci-Fi", rating: "8.5",
        description: "Life in a post-nuclear future.",
        media_type: "series",
    },
];

// ── WASM ABI exports — generated by macro ─────────────────────────────────────
stui_export_plugin!(HelloProvider);
